var jackpots = [
    {
       "PackageID":573,
       "ProductType":"Bundle",
       "ProductSubType":"lotteries",
       "IsMulti":false,
       "IsGift":false,
       "DisplayName":"10 EU Millions Quick Picks",
       "DisplayNameDE":"10 EU Millions Quick Picks",
       "IsIncentive":false,
       "IsDiscount":false,
       "EditableLines":true,
       "PackagePrice":"25.00",
       "OriginPrice":"25.00",
       "IsSubscription":0,
       "BillingPeriod":0,
       "DrawCount":"1",
       "Duration":null,
       "Discounts":[
 
       ],
       "TotalLines":10,
       "TotalSingleLines":10,
       "TotalTeamplayLines":0,
       "TotalDraws":1,
       "TotalGameTickets":0,
       "TicketsCount":0,
       "DisplayNames":{
          "en":"10 EU Millions Quick Picks",
          "de":"10 EU Millions Quick Picks"
       },
       "Items":[
          {
             "ProductID":"0",
             "LotteryID":"26",
             "LotteryName":"EU Millions",
             "ItemPrice":"2.50",
             "JackpotAmount":74000000,
             "RoundedJackpot":74000000,
             "LotteryCurrency":"EUR",
             "ParticipationDays":{
                "0":"Tuesday",
                "1":"Friday"
             },
             "TotalLines":10,
             "PickedNumbers":[
                {
                   "BasePick":[
                      "10",
                      "22",
                      "30",
                      "37",
                      "40"
                   ],
                   "ExtraPick":[
                      "3",
                      "4"
                   ]
                },
                {
                   "BasePick":[
                      "2",
                      "11",
                      "24",
                      "37",
                      "40"
                   ],
                   "ExtraPick":[
                      "1",
                      "6"
                   ]
                },
                {
                   "BasePick":[
                      "24",
                      "29",
                      "39",
                      "45",
                      "47"
                   ],
                   "ExtraPick":[
                      "11",
                      "12"
                   ]
                },
                {
                   "BasePick":[
                      "3",
                      "11",
                      "19",
                      "30",
                      "43"
                   ],
                   "ExtraPick":[
                      "3",
                      "12"
                   ]
                },
                {
                   "BasePick":[
                      "6",
                      "18",
                      "25",
                      "33",
                      "38"
                   ],
                   "ExtraPick":[
                      "6",
                      "9"
                   ]
                },
                {
                   "BasePick":[
                      "10",
                      "15",
                      "20",
                      "25",
                      "35"
                   ],
                   "ExtraPick":[
                      "1",
                      "9"
                   ]
                },
                {
                   "BasePick":[
                      "2",
                      "34",
                      "36",
                      "39",
                      "45"
                   ],
                   "ExtraPick":[
                      "9",
                      "12"
                   ]
                },
                {
                   "BasePick":[
                      "10",
                      "13",
                      "22",
                      "25",
                      "35"
                   ],
                   "ExtraPick":[
                      "5",
                      "7"
                   ]
                },
                {
                   "BasePick":[
                      "2",
                      "6",
                      "12",
                      "25",
                      "44"
                   ],
                   "ExtraPick":[
                      "2",
                      "6"
                   ]
                },
                {
                   "BasePick":[
                      "10",
                      "22",
                      "32",
                      "37",
                      "50"
                   ],
                   "ExtraPick":[
                      "8",
                      "9"
                   ]
                }
             ],
             "LotteryLink":"eumillions",
             "jackpotAsStringRounded":[
                "74",
                " Million"
             ],
             "jackpotAsString":[
                "74.0",
                " million"
             ],
             "currency":"€"
          }
       ]
    },
    {
       "PackageID":572,
       "ProductType":"Bundle",
       "ProductSubType":"lotteries",
       "IsMulti":false,
       "IsGift":false,
       "DisplayName":"6 Eurojackpot Quick Picks",
       "DisplayNameDE":"6 Eurojackpot Quick Picks",
       "IsIncentive":false,
       "IsDiscount":false,
       "EditableLines":true,
       "PackagePrice":"15.00",
       "OriginPrice":"15.00",
       "IsSubscription":0,
       "BillingPeriod":0,
       "DrawCount":"1",
       "Duration":null,
       "Discounts":[
 
       ],
       "TotalLines":6,
       "TotalSingleLines":6,
       "TotalTeamplayLines":0,
       "TotalDraws":1,
       "TotalGameTickets":0,
       "TicketsCount":0,
       "DisplayNames":{
          "en":"6 Eurojackpot Quick Picks",
          "de":"6 Eurojackpot Quick Picks"
       },
       "Items":[
          {
             "ProductID":"0",
             "LotteryID":"28",
             "LotteryName":"EuroJackpot",
             "ItemPrice":"2.50",
             "JackpotAmount":10000000,
             "RoundedJackpot":10000000,
             "LotteryCurrency":"EUR",
             "ParticipationDays":{
                "0":"Friday"
             },
             "TotalLines":6,
             "PickedNumbers":[
                {
                   "BasePick":[
                      "13",
                      "22",
                      "31",
                      "34",
                      "47"
                   ],
                   "ExtraPick":[
                      "2",
                      "9"
                   ]
                },
                {
                   "BasePick":[
                      "8",
                      "12",
                      "23",
                      "25",
                      "32"
                   ],
                   "ExtraPick":[
                      "3",
                      "9"
                   ]
                },
                {
                   "BasePick":[
                      "3",
                      "11",
                      "12",
                      "37",
                      "49"
                   ],
                   "ExtraPick":[
                      "3",
                      "5"
                   ]
                },
                {
                   "BasePick":[
                      "10",
                      "11",
                      "17",
                      "43",
                      "49"
                   ],
                   "ExtraPick":[
                      "2",
                      "4"
                   ]
                },
                {
                   "BasePick":[
                      "15",
                      "27",
                      "30",
                      "35",
                      "43"
                   ],
                   "ExtraPick":[
                      "7",
                      "10"
                   ]
                },
                {
                   "BasePick":[
                      "18",
                      "25",
                      "40",
                      "42",
                      "46"
                   ],
                   "ExtraPick":[
                      "4",
                      "9"
                   ]
                }
             ],
             "LotteryLink":"eurojackpot",
             "jackpotAsStringRounded":[
                "10",
                " Million"
             ],
             "jackpotAsString":[
                "10.0",
                " million"
             ],
             "currency":"€"
          }
       ]
    },
    {
       "PackageID":200,
       "ProductType":"Bundle",
       "ProductSubType":"lotteries",
       "IsMulti":false,
       "IsGift":false,
       "DisplayName":"Special Offer 1 - MegaMillions",
       "DisplayNameDE":"Special Offer 1 - MegaMillions",
       "IsIncentive":false,
       "IsDiscount":false,
       "EditableLines":true,
       "PackagePrice":"19.20",
       "OriginPrice":"19.20",
       "IsSubscription":0,
       "BillingPeriod":0,
       "DrawCount":"1",
       "Duration":null,
       "Discounts":[
 
       ],
       "TotalLines":6,
       "TotalSingleLines":6,
       "TotalTeamplayLines":0,
       "TotalDraws":1,
       "TotalGameTickets":0,
       "TicketsCount":0,
       "DisplayNames":{
          "en":"Special Offer 1 - MegaMillions",
          "de":"Special Offer 1 - MegaMillions"
       },
       "Items":[
          {
             "ProductID":"0",
             "LotteryID":"33",
             "LotteryName":"MegaMillions",
             "ItemPrice":"3.20",
             "JackpotAmount":84175084,
             "RoundedJackpot":84200000,
             "LotteryCurrency":"EUR",
             "ParticipationDays":{
                "0":"Tuesday",
                "1":"Friday"
             },
             "TotalLines":6,
             "PickedNumbers":[
                {
                   "BasePick":[
                      "11",
                      "13",
                      "51",
                      "67",
                      "68"
                   ],
                   "ExtraPick":[
                      "1"
                   ]
                },
                {
                   "BasePick":[
                      "2",
                      "3",
                      "36",
                      "56",
                      "59"
                   ],
                   "ExtraPick":[
                      "17"
                   ]
                },
                {
                   "BasePick":[
                      "13",
                      "16",
                      "45",
                      "53",
                      "67"
                   ],
                   "ExtraPick":[
                      "16"
                   ]
                },
                {
                   "BasePick":[
                      "4",
                      "47",
                      "48",
                      "58",
                      "60"
                   ],
                   "ExtraPick":[
                      "22"
                   ]
                },
                {
                   "BasePick":[
                      "5",
                      "23",
                      "24",
                      "49",
                      "54"
                   ],
                   "ExtraPick":[
                      "23"
                   ]
                },
                {
                   "BasePick":[
                      "37",
                      "53",
                      "55",
                      "60",
                      "65"
                   ],
                   "ExtraPick":[
                      "2"
                   ]
                }
             ],
             "LotteryLink":"megamillions",
             "jackpotAsStringRounded":[
                "84.2",
                " Million"
             ],
             "jackpotAsString":[
                "84.2",
                " million"
             ],
             "currency":"€"
          }
       ]
    }
 ];

class myApp {
       
    constructor(obj){
        this.obj = obj;
    }
    
    prepareElement(obj){
        let item = 
        `<div class="jackpot_wrapper"> 
            <div class="jackpot_name">${obj.DisplayName}</div>
            <div class="jackpot_price">${obj.PackagePrice}</div>
        </div>`;

        return item;
    };

    getData() {
        const elements = this.obj
                                .map(this.prepareElement)
                                .join('');
        return elements;
    };

    pushData(){
        let parent = document.getElementById('objects_holder');
        parent.innerHTML = this.getData();
    };

    run(){
        this.pushData();


    }

}
